### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by ananthakumar9794** [dandynaufaldi/particle-swarm-optimized-clustering#2]
can you give the explanation document for this project

**Comment by ananthakumar9794** [comment]
> document

but who is reply

**Comment by ananthakumar9794** [comment]
> can you give the explanation document for this project

who is the reply to my question? the second question, I'm asked today but the reply is dec month replied

**Comment by dandynaufaldi** [comment]
@ananthakumar9794 sorry for such incomplete repo
for usage example you can check on the [notebook](https://github.com/dandynaufaldi/particle-swarm-optimized-clustering/blob/master/Untitled.ipynb)
